name: music_server
description: A stateless music server written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  uuid: ^4.2.1
  isar: ^3.1.0+1
  path: ^1.8.3
  cryptography: ^2.7.0
  email_validator: ^2.1.17
  collection: ^1.18.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  crypto: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1
  lints: ^3.0.0