name: music_server
description: A stateless music server written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.2

dependencies:
  stateless_server:
    path: ../stateless_server
  uuid: ^4.2.1
  isar: ^4.0.0-dev.14
  path: ^1.8.3
  cryptography: ^2.7.0
  email_validator: ^2.1.17

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^3.0.0
  test: ^1.24.0
